<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class ExpertServicesPackagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('expert_services_packages')->delete();

        DB::table('expert_services_packages')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'service_type' => 'basic',
                    'service_price' => 10,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '["15 scholarships that anyone looking to study in the U.S. can apply for. Deadlines in each month."]',
                    'service_id' => 1,
                    'created_at' => '2023-04-05 09:26:41',
                    'updated_at' => '2023-04-05 09:26:41',
                    'deleted_at' => NULL,
                ),
            1 =>
                array(
                    'id' => 2,
                    'service_type' => 'standard',
                    'service_price' => 20,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '["35 scholarships that anyone looking to study in the U.S. can apply for. Deadlines in each month."]',
                    'service_id' => 1,
                    'created_at' => '2023-04-05 09:26:41',
                    'updated_at' => '2023-04-05 09:26:41',
                    'deleted_at' => NULL,
                ),
            2 =>
                array(
                    'id' => 3,
                    'service_type' => 'premium',
                    'service_price' => 30,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '["50 scholarships that anyone looking to study in the U.S. can apply for. Deadlines in each month."]',
                    'service_id' => 1,
                    'created_at' => '2023-04-05 09:26:41',
                    'updated_at' => '2023-04-05 09:26:41',
                    'deleted_at' => NULL,
                ),
            3 =>
                array(
                    'id' => 4,
                    'service_type' => 'basic',
                    'service_price' => 30,
                    'delivery_time' => 3,
                    'revision_limit' => '1',
                    'feature_description' => '[null]',
                    'service_id' => 2,
                    'created_at' => '2023-04-06 14:06:32',
                    'updated_at' => '2023-07-06 21:41:07',
                    'deleted_at' => NULL,
                ),
            4 =>
                array(
                    'id' => 5,
                    'service_type' => 'standard',
                    'service_price' => 50,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '[null]',
                    'service_id' => 2,
                    'created_at' => '2023-04-06 14:06:32',
                    'updated_at' => '2023-04-06 14:06:32',
                    'deleted_at' => NULL,
                ),
            5 =>
                array(
                    'id' => 6,
                    'service_type' => 'premium',
                    'service_price' => 100,
                    'delivery_time' => 6,
                    'revision_limit' => '3',
                    'feature_description' => '[null]',
                    'service_id' => 2,
                    'created_at' => '2023-04-06 14:06:32',
                    'updated_at' => '2023-04-06 14:06:32',
                    'deleted_at' => NULL,
                ),
            6 =>
                array(
                    'id' => 7,
                    'service_type' => 'basic',
                    'service_price' => 300,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '[null]',
                    'service_id' => 3,
                    'created_at' => '2023-04-13 15:03:58',
                    'updated_at' => '2023-04-13 15:03:58',
                    'deleted_at' => NULL,
                ),
            7 =>
                array(
                    'id' => 8,
                    'service_type' => 'basic',
                    'service_price' => 600,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast delivery"]',
                    'service_id' => 4,
                    'created_at' => '2023-04-13 18:19:42',
                    'updated_at' => '2023-04-15 14:40:35',
                    'deleted_at' => '2023-04-15 14:40:35',
                ),
            8 =>
                array(
                    'id' => 9,
                    'service_type' => 'basic',
                    'service_price' => 100,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '[null]',
                    'service_id' => 5,
                    'created_at' => '2023-04-14 11:24:33',
                    'updated_at' => '2023-04-14 11:24:33',
                    'deleted_at' => NULL,
                ),
            9 =>
                array(
                    'id' => 10,
                    'service_type' => 'standard',
                    'service_price' => 150,
                    'delivery_time' => 1,
                    'revision_limit' => '2',
                    'feature_description' => '[null]',
                    'service_id' => 5,
                    'created_at' => '2023-04-14 11:24:33',
                    'updated_at' => '2023-04-14 11:24:33',
                    'deleted_at' => NULL,
                ),
            10 =>
                array(
                    'id' => 11,
                    'service_type' => 'premium',
                    'service_price' => 200,
                    'delivery_time' => 1,
                    'revision_limit' => '2',
                    'feature_description' => '[null]',
                    'service_id' => 5,
                    'created_at' => '2023-04-14 11:24:33',
                    'updated_at' => '2023-04-14 11:24:33',
                    'deleted_at' => NULL,
                ),
            11 =>
                array(
                    'id' => 12,
                    'service_type' => 'basic',
                    'service_price' => 10,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '[null]',
                    'service_id' => 6,
                    'created_at' => '2023-04-14 11:29:48',
                    'updated_at' => '2023-04-14 11:29:48',
                    'deleted_at' => NULL,
                ),
            12 =>
                array(
                    'id' => 13,
                    'service_type' => 'standard',
                    'service_price' => 15,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '[null]',
                    'service_id' => 6,
                    'created_at' => '2023-04-14 11:29:48',
                    'updated_at' => '2023-04-14 11:29:48',
                    'deleted_at' => NULL,
                ),
            13 =>
                array(
                    'id' => 14,
                    'service_type' => 'premium',
                    'service_price' => 20,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '[null]',
                    'service_id' => 6,
                    'created_at' => '2023-04-14 11:29:48',
                    'updated_at' => '2023-04-14 11:29:48',
                    'deleted_at' => NULL,
                ),
            14 =>
                array(
                    'id' => 15,
                    'service_type' => 'basic',
                    'service_price' => 200,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast delivery"]',
                    'service_id' => 7,
                    'created_at' => '2023-04-14 11:47:29',
                    'updated_at' => '2023-04-15 14:45:04',
                    'deleted_at' => '2023-04-15 14:45:04',
                ),
            15 =>
                array(
                    'id' => 16,
                    'service_type' => 'basic',
                    'service_price' => 600,
                    'delivery_time' => 3,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast delivery"]',
                    'service_id' => 8,
                    'created_at' => '2023-04-14 11:49:18',
                    'updated_at' => '2023-04-15 14:47:54',
                    'deleted_at' => '2023-04-15 14:47:54',
                ),
            16 =>
                array(
                    'id' => 17,
                    'service_type' => 'basic',
                    'service_price' => 500,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast delivery"]',
                    'service_id' => 9,
                    'created_at' => '2023-04-14 11:55:08',
                    'updated_at' => '2023-04-15 14:50:44',
                    'deleted_at' => '2023-04-15 14:50:44',
                ),
            17 =>
                array(
                    'id' => 18,
                    'service_type' => 'basic',
                    'service_price' => 300,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '["Fast delivery"]',
                    'service_id' => 10,
                    'created_at' => '2023-04-14 12:04:53',
                    'updated_at' => '2023-04-15 14:31:35',
                    'deleted_at' => '2023-04-15 14:31:35',
                ),
            18 =>
                array(
                    'id' => 19,
                    'service_type' => 'basic',
                    'service_price' => 100,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '[null]',
                    'service_id' => 11,
                    'created_at' => '2023-04-14 12:41:13',
                    'updated_at' => '2023-04-15 14:34:02',
                    'deleted_at' => '2023-04-15 14:34:02',
                ),
            19 =>
                array(
                    'id' => 20,
                    'service_type' => 'basic',
                    'service_price' => 30,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '[null]',
                    'service_id' => 12,
                    'created_at' => '2023-04-14 12:51:16',
                    'updated_at' => '2023-04-14 12:51:16',
                    'deleted_at' => NULL,
                ),
            20 =>
                array(
                    'id' => 21,
                    'service_type' => 'standard',
                    'service_price' => 80,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '[null]',
                    'service_id' => 12,
                    'created_at' => '2023-04-14 12:51:16',
                    'updated_at' => '2023-04-14 12:51:16',
                    'deleted_at' => NULL,
                ),
            21 =>
                array(
                    'id' => 22,
                    'service_type' => 'premium',
                    'service_price' => 100,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '[null]',
                    'service_id' => 12,
                    'created_at' => '2023-04-14 12:51:16',
                    'updated_at' => '2023-04-14 12:51:16',
                    'deleted_at' => NULL,
                ),
            22 =>
                array(
                    'id' => 23,
                    'service_type' => 'basic',
                    'service_price' => 600,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast delivery"]',
                    'service_id' => 13,
                    'created_at' => '2023-04-15 01:44:04',
                    'updated_at' => '2023-04-15 01:44:41',
                    'deleted_at' => '2023-04-15 01:44:41',
                ),
            23 =>
                array(
                    'id' => 24,
                    'service_type' => 'basic',
                    'service_price' => 300,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Standard work"]',
                    'service_id' => 14,
                    'created_at' => '2023-04-15 14:19:21',
                    'updated_at' => '2023-04-15 14:22:39',
                    'deleted_at' => '2023-04-15 14:22:39',
                ),
            24 =>
                array(
                    'id' => 25,
                    'service_type' => 'basic',
                    'service_price' => 300,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Standard work"]',
                    'service_id' => 15,
                    'created_at' => '2023-04-15 14:20:52',
                    'updated_at' => '2023-04-15 14:22:43',
                    'deleted_at' => '2023-04-15 14:22:43',
                ),
            25 =>
                array(
                    'id' => 26,
                    'service_type' => 'premium',
                    'service_price' => 500,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '["fast delivery"]',
                    'service_id' => 15,
                    'created_at' => '2023-04-15 14:20:52',
                    'updated_at' => '2023-04-15 14:22:43',
                    'deleted_at' => '2023-04-15 14:22:43',
                ),
            26 =>
                array(
                    'id' => 27,
                    'service_type' => 'basic',
                    'service_price' => 300,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Standard work","Fact-Checking"]',
                    'service_id' => 16,
                    'created_at' => '2023-04-15 14:22:18',
                    'updated_at' => '2023-04-15 15:13:30',
                    'deleted_at' => NULL,
                ),
            27 =>
                array(
                    'id' => 28,
                    'service_type' => 'standard',
                    'service_price' => 400,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["fast delivery","Structural Edit","Print Layout"]',
                    'service_id' => 16,
                    'created_at' => '2023-04-15 14:22:18',
                    'updated_at' => '2023-04-15 15:13:30',
                    'deleted_at' => NULL,
                ),
            28 =>
                array(
                    'id' => 29,
                    'service_type' => 'premium',
                    'service_price' => 500,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '["fast delivery","Grammar & Syntax Review","Content Rewriting","Fact-Checking","Print Layout","Structural Edit"]',
                    'service_id' => 16,
                    'created_at' => '2023-04-15 14:22:18',
                    'updated_at' => '2023-04-15 15:13:30',
                    'deleted_at' => NULL,
                ),
            29 =>
                array(
                    'id' => 30,
                    'service_type' => 'basic',
                    'service_price' => 200,
                    'delivery_time' => 7,
                    'revision_limit' => '3',
                    'feature_description' => '["Standard work","Affordable service"]',
                    'service_id' => 17,
                    'created_at' => '2023-04-15 14:30:56',
                    'updated_at' => '2023-07-06 21:47:39',
                    'deleted_at' => NULL,
                ),
            30 =>
                array(
                    'id' => 31,
                    'service_type' => 'standard',
                    'service_price' => 400,
                    'delivery_time' => 3,
                    'revision_limit' => '2',
                    'feature_description' => '["fast delivery","Structural Edit","Print Layout"]',
                    'service_id' => 17,
                    'created_at' => '2023-04-15 14:30:56',
                    'updated_at' => '2023-04-15 15:10:05',
                    'deleted_at' => NULL,
                ),
            31 =>
                array(
                    'id' => 32,
                    'service_type' => 'premium',
                    'service_price' => 500,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '["Fact-Checking","Content Rewriting","Grammar & Syntax Review","Super Fast Delivery","Structural Edit"]',
                    'service_id' => 17,
                    'created_at' => '2023-04-15 14:30:56',
                    'updated_at' => '2023-04-15 15:10:05',
                    'deleted_at' => NULL,
                ),
            32 =>
                array(
                    'id' => 33,
                    'service_type' => 'basic',
                    'service_price' => 100,
                    'delivery_time' => 4,
                    'revision_limit' => '1',
                    'feature_description' => '["Standard work","Free correction"]',
                    'service_id' => 18,
                    'created_at' => '2023-04-15 14:33:56',
                    'updated_at' => '2023-04-15 15:11:42',
                    'deleted_at' => NULL,
                ),
            33 =>
                array(
                    'id' => 34,
                    'service_type' => 'standard',
                    'service_price' => 350,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["fast delivery","Print Layout","Grammar & Syntax Review"]',
                    'service_id' => 18,
                    'created_at' => '2023-04-15 14:33:56',
                    'updated_at' => '2023-04-15 15:11:42',
                    'deleted_at' => NULL,
                ),
            34 =>
                array(
                    'id' => 35,
                    'service_type' => 'premium',
                    'service_price' => 400,
                    'delivery_time' => 1,
                    'revision_limit' => '3',
                    'feature_description' => '["fast delivery","Fact-Checking","Content Rewriting","Structural Edit","Grammar & Syntax Review"]',
                    'service_id' => 18,
                    'created_at' => '2023-04-15 14:33:56',
                    'updated_at' => '2023-04-15 15:11:42',
                    'deleted_at' => NULL,
                ),
            35 =>
                array(
                    'id' => 36,
                    'service_type' => 'basic',
                    'service_price' => 100,
                    'delivery_time' => 5,
                    'revision_limit' => '1',
                    'feature_description' => '["Free correction","Standard work"]',
                    'service_id' => 19,
                    'created_at' => '2023-04-15 14:40:28',
                    'updated_at' => '2023-04-15 14:42:06',
                    'deleted_at' => NULL,
                ),
            36 =>
                array(
                    'id' => 37,
                    'service_type' => 'standard',
                    'service_price' => 200,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast Delivery","Structural Edit","Grammar & Syntax Review"]',
                    'service_id' => 19,
                    'created_at' => '2023-04-15 14:40:28',
                    'updated_at' => '2023-04-15 15:02:25',
                    'deleted_at' => NULL,
                ),
            37 =>
                array(
                    'id' => 38,
                    'service_type' => 'premium',
                    'service_price' => 400,
                    'delivery_time' => 1,
                    'revision_limit' => '4',
                    'feature_description' => '["Super Fast Delivery","Grammar & Syntax Review","Print Layout","Fact-Checking","Content Rewriting"]',
                    'service_id' => 19,
                    'created_at' => '2023-04-15 14:40:28',
                    'updated_at' => '2023-04-15 15:02:25',
                    'deleted_at' => NULL,
                ),
            38 =>
                array(
                    'id' => 39,
                    'service_type' => 'basic',
                    'service_price' => 80,
                    'delivery_time' => 3,
                    'revision_limit' => '1',
                    'feature_description' => '["Free correction","Fact-Checking"]',
                    'service_id' => 20,
                    'created_at' => '2023-04-15 14:44:57',
                    'updated_at' => '2023-07-06 21:51:11',
                    'deleted_at' => NULL,
                ),
            39 =>
                array(
                    'id' => 40,
                    'service_type' => 'standard',
                    'service_price' => 150,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast Delivery","Print Layout","Grammar & Syntax Review"]',
                    'service_id' => 20,
                    'created_at' => '2023-04-15 14:44:57',
                    'updated_at' => '2023-04-15 15:04:10',
                    'deleted_at' => NULL,
                ),
            40 =>
                array(
                    'id' => 41,
                    'service_type' => 'premium',
                    'service_price' => 300,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '["Super Fast Delivery","Content Rewriting","Fact-Checking","Structural Edit","Grammar & Syntax Review"]',
                    'service_id' => 20,
                    'created_at' => '2023-04-15 14:44:57',
                    'updated_at' => '2023-04-15 15:04:10',
                    'deleted_at' => NULL,
                ),
            41 =>
                array(
                    'id' => 42,
                    'service_type' => 'basic',
                    'service_price' => 100,
                    'delivery_time' => 4,
                    'revision_limit' => '1',
                    'feature_description' => '["Free correction","Fact-Checking"]',
                    'service_id' => 21,
                    'created_at' => '2023-04-15 14:47:48',
                    'updated_at' => '2023-04-15 15:05:31',
                    'deleted_at' => NULL,
                ),
            42 =>
                array(
                    'id' => 43,
                    'service_type' => 'standard',
                    'service_price' => 150,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast Delivery","Structural Edit","Print Layout"]',
                    'service_id' => 21,
                    'created_at' => '2023-04-15 14:47:48',
                    'updated_at' => '2023-04-15 15:05:31',
                    'deleted_at' => NULL,
                ),
            43 =>
                array(
                    'id' => 44,
                    'service_type' => 'premium',
                    'service_price' => 250,
                    'delivery_time' => 1,
                    'revision_limit' => '3',
                    'feature_description' => '["Super Fast Delivery","Grammar & Syntax Review","Content Rewriting","Print Layout","Structural Edit"]',
                    'service_id' => 21,
                    'created_at' => '2023-04-15 14:47:48',
                    'updated_at' => '2023-04-15 15:05:31',
                    'deleted_at' => NULL,
                ),
            44 =>
                array(
                    'id' => 45,
                    'service_type' => 'basic',
                    'service_price' => 100,
                    'delivery_time' => 3,
                    'revision_limit' => '1',
                    'feature_description' => '["Standard work","Free correction"]',
                    'service_id' => 22,
                    'created_at' => '2023-04-15 14:50:37',
                    'updated_at' => '2023-04-15 15:06:37',
                    'deleted_at' => NULL,
                ),
            45 =>
                array(
                    'id' => 46,
                    'service_type' => 'standard',
                    'service_price' => 150,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast Delivery","Structural Edit","Print Layout","Grammar & Syntax Review","Fact-Checking"]',
                    'service_id' => 22,
                    'created_at' => '2023-04-15 14:50:37',
                    'updated_at' => '2023-04-15 15:06:37',
                    'deleted_at' => NULL,
                ),
            46 =>
                array(
                    'id' => 47,
                    'service_type' => 'premium',
                    'service_price' => 250,
                    'delivery_time' => 1,
                    'revision_limit' => '3',
                    'feature_description' => '["Super Fast Delivery"]',
                    'service_id' => 22,
                    'created_at' => '2023-04-15 14:50:37',
                    'updated_at' => '2023-04-15 14:50:37',
                    'deleted_at' => NULL,
                ),
            47 =>
                array(
                    'id' => 48,
                    'service_type' => 'basic',
                    'service_price' => 100,
                    'delivery_time' => 4,
                    'revision_limit' => '2',
                    'feature_description' => '["Standard work","Fact-Checking"]',
                    'service_id' => 23,
                    'created_at' => '2023-04-15 17:41:38',
                    'updated_at' => '2023-04-15 17:41:38',
                    'deleted_at' => NULL,
                ),
            48 =>
                array(
                    'id' => 49,
                    'service_type' => 'standard',
                    'service_price' => 150,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Structural Edit","Print Layout","Grammar & Syntax Review"]',
                    'service_id' => 23,
                    'created_at' => '2023-04-15 17:41:38',
                    'updated_at' => '2023-04-15 17:41:38',
                    'deleted_at' => NULL,
                ),
            49 =>
                array(
                    'id' => 50,
                    'service_type' => 'premium',
                    'service_price' => 300,
                    'delivery_time' => 1,
                    'revision_limit' => '1',
                    'feature_description' => '["Super Fast Delivery","Content Rewriting","Grammar & Syntax Review","Fact-Checking","Structural Edit"]',
                    'service_id' => 23,
                    'created_at' => '2023-04-15 17:41:38',
                    'updated_at' => '2023-04-15 17:41:38',
                    'deleted_at' => NULL,
                ),
            50 =>
                array(
                    'id' => 51,
                    'service_type' => 'basic',
                    'service_price' => 100,
                    'delivery_time' => 3,
                    'revision_limit' => '2',
                    'feature_description' => '["Fast delivery","Standard work"]',
                    'service_id' => 24,
                    'created_at' => '2023-06-06 15:31:31',
                    'updated_at' => '2023-06-06 15:31:31',
                    'deleted_at' => NULL,
                ),
            51 =>
                array(
                    'id' => 52,
                    'service_type' => 'standard',
                    'service_price' => 200,
                    'delivery_time' => 2,
                    'revision_limit' => '2',
                    'feature_description' => '["Complexity solving","Structural Edit","Print Layout"]',
                    'service_id' => 24,
                    'created_at' => '2023-06-06 15:31:31',
                    'updated_at' => '2023-06-06 15:31:31',
                    'deleted_at' => NULL,
                ),
            52 =>
                array(
                    'id' => 53,
                    'service_type' => 'premium',
                    'service_price' => 400,
                    'delivery_time' => 1,
                    'revision_limit' => '5',
                    'feature_description' => '["Content Rewriting","Grammar & Syntax Review","Super Fast Delivery","Will cover everything"]',
                    'service_id' => 24,
                    'created_at' => '2023-06-06 15:31:31',
                    'updated_at' => '2023-06-06 15:31:31',
                    'deleted_at' => NULL,
                ),
        ));
    }
}
