<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class NotificationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('notifications')->delete();

        DB::table('notifications')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 5,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-04-06 12:36:52',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            1 =>
                array(
                    'id' => 2,
                    'notification_type' => 'expert_withdrawal_request',
                    'sender_id' => 4,
                    'receiver_id' => 0,
                    'message' => 'A new withdrawal has been requested by',
                    'link' => '/admin/withdraw-requests',
                    'created_at' => '2023-04-06 12:56:39',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            2 =>
                array(
                    'id' => 3,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 7,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-04-06 14:09:31',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            3 =>
                array(
                    'id' => 4,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 7,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/phd-scholarship-proposal20230406-022619',
                    'created_at' => '2023-04-06 14:26:19',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            4 =>
                array(
                    'id' => 5,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 5,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/advisor-needed-for-my-future-study20230406-051014',
                    'created_at' => '2023-04-06 17:10:14',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            5 =>
                array(
                    'id' => 6,
                    'notification_type' => 'expert_bid_on_project',
                    'sender_id' => 4,
                    'receiver_id' => 5,
                    'message' => 'A new bid has been submitted by',
                    'link' => '/project/advisor-needed-for-my-future-study20230406-051014',
                    'created_at' => '2023-04-06 17:15:17',
                    'updated_at' => '2023-04-06 17:15:17',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            6 =>
                array(
                    'id' => 7,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 9,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/thesis-proofreading-and-editing-service20230406-055734',
                    'created_at' => '2023-04-06 17:57:34',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            7 =>
                array(
                    'id' => 8,
                    'notification_type' => 'expert_bid_on_project',
                    'sender_id' => 8,
                    'receiver_id' => 9,
                    'message' => 'A new bid has been submitted by',
                    'link' => '/project/thesis-proofreading-and-editing-service20230406-055734',
                    'created_at' => '2023-04-06 17:59:27',
                    'updated_at' => '2023-04-06 17:59:27',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            8 =>
                array(
                    'id' => 9,
                    'notification_type' => 'freelancer_hired_for_project',
                    'sender_id' => 9,
                    'receiver_id' => 8,
                    'message' => 'You have been hired for a project by',
                    'link' => '/project/thesis-proofreading-and-editing-service20230406-055734',
                    'created_at' => '2023-04-06 18:07:36',
                    'updated_at' => '2023-04-06 18:07:36',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            9 =>
                array(
                    'id' => 10,
                    'notification_type' => 'milestone_payment_request_to_client',
                    'sender_id' => 8,
                    'receiver_id' => 9,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/recieved-milestone-requests',
                    'created_at' => '2023-04-06 18:10:27',
                    'updated_at' => '2023-04-06 18:10:27',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            10 =>
                array(
                    'id' => 11,
                    'notification_type' => 'milestone_payment_request_to_admin',
                    'sender_id' => 8,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-04-06 18:10:27',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            11 =>
                array(
                    'id' => 12,
                    'notification_type' => 'freelancer_bid_on_project',
                    'sender_id' => 6,
                    'receiver_id' => 5,
                    'message' => 'A new bid has been submitted by',
                    'link' => '/project/advisor-needed-for-my-future-study20230406-051014',
                    'created_at' => '2023-04-06 18:17:28',
                    'updated_at' => '2023-04-06 18:17:28',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            12 =>
                array(
                    'id' => 13,
                    'notification_type' => 'freelancer_bid_on_project',
                    'sender_id' => 8,
                    'receiver_id' => 5,
                    'message' => 'A new bid has been submitted by',
                    'link' => '/project/advisor-needed-for-my-future-study20230406-051014',
                    'created_at' => '2023-04-13 15:11:44',
                    'updated_at' => '2023-04-13 15:11:44',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            13 =>
                array(
                    'id' => 14,
                    'notification_type' => 'milestone_payments_done_to_freelancer',
                    'sender_id' => 9,
                    'receiver_id' => 8,
                    'message' => 'Your milestone payment request has been accepted by',
                    'link' => '/sent-milestone-requests',
                    'created_at' => '2023-04-13 17:22:04',
                    'updated_at' => '2023-04-13 17:22:04',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            14 =>
                array(
                    'id' => 15,
                    'notification_type' => 'milestone_payments_done_to_admin',
                    'sender_id' => 9,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment request has been accepted by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-04-13 17:22:04',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            15 =>
                array(
                    'id' => 16,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 9,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/looking-for-suitable-scholarships20230413-052857',
                    'created_at' => '2023-04-13 17:28:57',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            16 =>
                array(
                    'id' => 17,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 9,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/looking-for-information-technology-scholarship-consultations20230413-053412',
                    'created_at' => '2023-04-13 17:34:12',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            17 =>
                array(
                    'id' => 18,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 9,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/mentor-need-for-my-future-studies20230413-054440',
                    'created_at' => '2023-04-13 17:44:40',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            18 =>
                array(
                    'id' => 19,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 12,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-04-13 18:16:30',
                    'updated_at' => '2023-04-13 18:22:18',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 1,
                ),
            19 =>
                array(
                    'id' => 20,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 7,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/admission-consultant-and-application-for-master-degree20230414-115113',
                    'created_at' => '2023-04-14 11:51:13',
                    'updated_at' => '2023-04-14 11:51:13',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            20 =>
                array(
                    'id' => 21,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 6,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-04-14 12:52:42',
                    'updated_at' => '2023-04-14 12:52:42',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            21 =>
                array(
                    'id' => 22,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 14,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-04-14 12:54:03',
                    'updated_at' => '2023-04-14 12:54:03',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            22 =>
                array(
                    'id' => 23,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 15,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/university-research20230414-010248',
                    'created_at' => '2023-04-14 13:02:48',
                    'updated_at' => '2023-04-14 13:02:48',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            23 =>
                array(
                    'id' => 24,
                    'notification_type' => 'freelancer_bid_on_project',
                    'sender_id' => 14,
                    'receiver_id' => 15,
                    'message' => 'A new bid has been submitted by',
                    'link' => '/project/university-research20230414-010248',
                    'created_at' => '2023-04-15 01:38:20',
                    'updated_at' => '2023-09-20 16:12:50',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 1,
                ),
            24 =>
                array(
                    'id' => 25,
                    'notification_type' => 'service_cancel_request_approved_by_admin',
                    'sender_id' => 1,
                    'receiver_id' => 6,
                    'message' => 'A Service cancellation is approved by ',
                    'link' => '/services/purchased',
                    'created_at' => '2023-04-15 06:36:13',
                    'updated_at' => '2023-04-15 06:36:13',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            25 =>
                array(
                    'id' => 26,
                    'notification_type' => 'service_cancel_request_approved_by_admin',
                    'sender_id' => 1,
                    'receiver_id' => 5,
                    'message' => 'A Service cancellation is approved by ',
                    'link' => '/services/purchased',
                    'created_at' => '2023-04-15 06:36:13',
                    'updated_at' => '2023-04-15 06:36:13',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            26 =>
                array(
                    'id' => 27,
                    'notification_type' => 'freelancer_withdrawal_request_accepted_by_admin',
                    'sender_id' => 1,
                    'receiver_id' => 4,
                    'message' => 'A new withdrawal request has been accepted by',
                    'link' => '/withdrawal-history',
                    'created_at' => '2023-04-15 06:38:10',
                    'updated_at' => '2023-04-15 06:38:10',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            27 =>
                array(
                    'id' => 28,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 18,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/proofread-and-edit-statement20230415-052908',
                    'created_at' => '2023-04-15 17:29:08',
                    'updated_at' => '2023-04-15 17:29:08',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            28 =>
                array(
                    'id' => 29,
                    'notification_type' => 'project_completed_by_client',
                    'sender_id' => 9,
                    'receiver_id' => 8,
                    'message' => 'A Project has been marked as completed by',
                    'link' => '/project/thesis-proofreading-and-editing-service20230406-055734',
                    'created_at' => '2023-04-15 18:06:04',
                    'updated_at' => '2023-04-15 18:06:04',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            29 =>
                array(
                    'id' => 30,
                    'notification_type' => 'freelancer_review_by_client',
                    'sender_id' => 9,
                    'receiver_id' => 8,
                    'message' => 'You have been given a review for a project by',
                    'link' => '/user-reviews/freelancer',
                    'created_at' => '2023-04-15 18:06:39',
                    'updated_at' => '2023-04-15 18:06:39',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            30 =>
                array(
                    'id' => 31,
                    'notification_type' => 'freelancer_hired_for_project',
                    'sender_id' => 5,
                    'receiver_id' => 4,
                    'message' => 'You have been hired for a project by',
                    'link' => '/project/advisor-needed-for-my-future-study20230406-051014',
                    'created_at' => '2023-04-15 18:11:13',
                    'updated_at' => '2023-04-15 18:11:13',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            31 =>
                array(
                    'id' => 32,
                    'notification_type' => 'freelancer_proposal_for_project',
                    'sender_id' => 5,
                    'receiver_id' => 4,
                    'message' => 'You have recieved a proposal for a project by',
                    'link' => '/project/education-writers-scholarships-and-travel-abroad20230415-061551',
                    'created_at' => '2023-04-15 18:15:51',
                    'updated_at' => '2023-04-15 18:15:51',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            32 =>
                array(
                    'id' => 33,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 20,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-05-11 23:45:20',
                    'updated_at' => '2023-05-11 23:45:20',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            33 =>
                array(
                    'id' => 34,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 21,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-05-21 18:58:50',
                    'updated_at' => '2023-05-21 18:58:50',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            34 =>
                array(
                    'id' => 35,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 22,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-06-05 09:08:15',
                    'updated_at' => '2023-06-05 09:08:15',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            35 =>
                array(
                    'id' => 36,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 23,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-06-07 03:46:34',
                    'updated_at' => '2023-06-07 03:46:34',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            36 =>
                array(
                    'id' => 37,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 23,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/looking-for-transcription-and-translition-helper20230607-035448',
                    'created_at' => '2023-06-07 03:54:48',
                    'updated_at' => '2023-06-07 03:54:48',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            37 =>
                array(
                    'id' => 38,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 23,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/need-a-experience-essay-research-and-summary-writer20230607-040202',
                    'created_at' => '2023-06-07 04:02:02',
                    'updated_at' => '2023-06-07 04:02:02',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            38 =>
                array(
                    'id' => 39,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 13,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-06-07 05:05:16',
                    'updated_at' => '2023-06-07 05:05:16',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            39 =>
                array(
                    'id' => 40,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 8,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-06-07 05:07:57',
                    'updated_at' => '2023-06-07 05:07:57',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            40 =>
                array(
                    'id' => 41,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 4,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-06-07 05:13:51',
                    'updated_at' => '2023-06-07 05:13:51',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            41 =>
                array(
                    'id' => 42,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 22,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-06-07 05:26:50',
                    'updated_at' => '2023-06-07 05:26:50',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            42 =>
                array(
                    'id' => 43,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 12,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-06-07 05:33:26',
                    'updated_at' => '2023-06-07 05:33:26',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            43 =>
                array(
                    'id' => 44,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 16,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-06-07 05:37:19',
                    'updated_at' => '2023-06-07 05:37:19',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            44 =>
                array(
                    'id' => 45,
                    'notification_type' => 'package_purchased',
                    'sender_id' => 21,
                    'receiver_id' => 0,
                    'message' => 'A new package has been purchased by',
                    'link' => '/admin/all-package-payments',
                    'created_at' => '2023-06-07 05:41:54',
                    'updated_at' => '2023-06-07 05:41:54',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            45 =>
                array(
                    'id' => 46,
                    'notification_type' => 'freelancer_bid_on_project',
                    'sender_id' => 6,
                    'receiver_id' => 23,
                    'message' => 'A new bid has been submitted by',
                    'link' => '/project/need-a-experience-essay-research-and-summary-writer20230607-040202',
                    'created_at' => '2023-07-05 13:27:04',
                    'updated_at' => '2023-07-05 13:27:04',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            46 =>
                array(
                    'id' => 47,
                    'notification_type' => 'freelancer_hired_for_project',
                    'sender_id' => 23,
                    'receiver_id' => 6,
                    'message' => 'You have been hired for a project by',
                    'link' => '/project/need-a-experience-essay-research-and-summary-writer20230607-040202',
                    'created_at' => '2023-07-05 13:32:30',
                    'updated_at' => '2023-07-05 13:32:30',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            47 =>
                array(
                    'id' => 48,
                    'notification_type' => 'milestone_payment_request_to_client',
                    'sender_id' => 6,
                    'receiver_id' => 23,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/recieved-milestone-requests',
                    'created_at' => '2023-07-05 13:35:19',
                    'updated_at' => '2023-07-05 13:35:19',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            48 =>
                array(
                    'id' => 49,
                    'notification_type' => 'milestone_payment_request_to_admin',
                    'sender_id' => 6,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-07-05 13:35:23',
                    'updated_at' => '2023-07-05 13:35:23',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            49 =>
                array(
                    'id' => 50,
                    'notification_type' => 'milestone_payments_done_to_freelancer',
                    'sender_id' => 23,
                    'receiver_id' => 6,
                    'message' => 'Your milestone payment request has been accepted by',
                    'link' => '/sent-milestone-requests',
                    'created_at' => '2023-07-05 13:36:40',
                    'updated_at' => '2023-07-05 13:36:40',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            50 =>
                array(
                    'id' => 51,
                    'notification_type' => 'milestone_payments_done_to_admin',
                    'sender_id' => 23,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment request has been accepted by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-07-05 13:36:45',
                    'updated_at' => '2023-07-05 13:36:45',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            51 =>
                array(
                    'id' => 52,
                    'notification_type' => 'project_completed_by_client',
                    'sender_id' => 23,
                    'receiver_id' => 6,
                    'message' => 'A Project has been marked as completed by',
                    'link' => '/project/need-a-experience-essay-research-and-summary-writer20230607-040202',
                    'created_at' => '2023-07-05 13:38:18',
                    'updated_at' => '2023-07-05 13:38:18',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            52 =>
                array(
                    'id' => 53,
                    'notification_type' => 'freelancer_review_by_client',
                    'sender_id' => 23,
                    'receiver_id' => 6,
                    'message' => 'You have been given a review for a project by',
                    'link' => '/user-reviews/freelancer',
                    'created_at' => '2023-07-05 13:38:52',
                    'updated_at' => '2023-07-05 13:38:52',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            53 =>
                array(
                    'id' => 54,
                    'notification_type' => 'client_review_by_freelancer',
                    'sender_id' => 6,
                    'receiver_id' => 23,
                    'message' => 'You have been given a review for a project by',
                    'link' => '/user-reviews/client',
                    'created_at' => '2023-07-05 13:39:28',
                    'updated_at' => '2023-07-05 13:39:28',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            54 =>
                array(
                    'id' => 55,
                    'notification_type' => 'freelancer_proposal_for_project',
                    'sender_id' => 5,
                    'receiver_id' => 4,
                    'message' => 'You have recieved a proposal for a project by',
                    'link' => '/project/university-research20230724-114304',
                    'created_at' => '2023-07-24 11:43:04',
                    'updated_at' => '2023-07-24 11:43:04',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            55 =>
                array(
                    'id' => 56,
                    'notification_type' => 'freelancer_hired_for_project',
                    'sender_id' => 4,
                    'receiver_id' => 4,
                    'message' => 'You have been hired for a project by',
                    'link' => '/project/education-writers-scholarships-and-travel-abroad20230415-061551',
                    'created_at' => '2023-07-24 11:46:07',
                    'updated_at' => '2023-07-24 11:46:07',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            56 =>
                array(
                    'id' => 57,
                    'notification_type' => 'freelancer_hired_for_project',
                    'sender_id' => 4,
                    'receiver_id' => 4,
                    'message' => 'You have been hired for a project by',
                    'link' => '/project/university-research20230724-114304',
                    'created_at' => '2023-07-24 11:46:26',
                    'updated_at' => '2023-07-24 11:46:26',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            57 =>
                array(
                    'id' => 58,
                    'notification_type' => 'milestone_payment_request_to_client',
                    'sender_id' => 4,
                    'receiver_id' => 5,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/recieved-milestone-requests',
                    'created_at' => '2023-07-24 11:48:32',
                    'updated_at' => '2023-07-24 11:48:32',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            58 =>
                array(
                    'id' => 59,
                    'notification_type' => 'milestone_payment_request_to_admin',
                    'sender_id' => 4,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-07-24 11:48:36',
                    'updated_at' => '2023-07-24 11:48:36',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            59 =>
                array(
                    'id' => 60,
                    'notification_type' => 'milestone_payment_request_to_client',
                    'sender_id' => 4,
                    'receiver_id' => 5,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/recieved-milestone-requests',
                    'created_at' => '2023-07-24 11:49:21',
                    'updated_at' => '2023-07-24 11:49:21',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            60 =>
                array(
                    'id' => 61,
                    'notification_type' => 'milestone_payment_request_to_admin',
                    'sender_id' => 4,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-07-24 11:49:25',
                    'updated_at' => '2023-07-24 11:49:25',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            61 =>
                array(
                    'id' => 62,
                    'notification_type' => 'milestone_payments_done_to_freelancer',
                    'sender_id' => 5,
                    'receiver_id' => 4,
                    'message' => 'Your milestone payment request has been accepted by',
                    'link' => '/sent-milestone-requests',
                    'created_at' => '2023-07-24 11:56:35',
                    'updated_at' => '2023-07-24 11:56:35',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            62 =>
                array(
                    'id' => 63,
                    'notification_type' => 'milestone_payments_done_to_admin',
                    'sender_id' => 5,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment request has been accepted by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-07-24 11:56:39',
                    'updated_at' => '2023-07-24 11:56:39',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            63 =>
                array(
                    'id' => 64,
                    'notification_type' => 'project_completed_by_client',
                    'sender_id' => 5,
                    'receiver_id' => 4,
                    'message' => 'A Project has been marked as completed by',
                    'link' => '/project/university-research20230724-114304',
                    'created_at' => '2023-07-24 11:57:02',
                    'updated_at' => '2023-07-24 11:57:02',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            64 =>
                array(
                    'id' => 65,
                    'notification_type' => 'freelancer_review_by_client',
                    'sender_id' => 5,
                    'receiver_id' => 4,
                    'message' => 'You have been given a review for a project by',
                    'link' => '/user-reviews/freelancer',
                    'created_at' => '2023-07-24 11:58:06',
                    'updated_at' => '2023-07-24 11:58:06',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            65 =>
                array(
                    'id' => 66,
                    'notification_type' => 'client_review_by_freelancer',
                    'sender_id' => 4,
                    'receiver_id' => 5,
                    'message' => 'You have been given a review for a project by',
                    'link' => '/user-reviews/client',
                    'created_at' => '2023-07-24 11:58:53',
                    'updated_at' => '2023-07-24 11:58:53',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            66 =>
                array(
                    'id' => 67,
                    'notification_type' => 'freelancer_withdrawal_request',
                    'sender_id' => 4,
                    'receiver_id' => 0,
                    'message' => 'A new withdrawal has been requested by',
                    'link' => '/admin/withdraw-requests',
                    'created_at' => '2023-07-24 12:00:24',
                    'updated_at' => '2023-07-24 12:00:24',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            67 =>
                array(
                    'id' => 68,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 5,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/need-a-experience-essay-research-and-summary-writer20230726-121040',
                    'created_at' => '2023-07-26 12:10:40',
                    'updated_at' => '2023-07-26 12:10:40',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            68 =>
                array(
                    'id' => 69,
                    'notification_type' => 'milestone_payments_done_to_freelancer',
                    'sender_id' => 5,
                    'receiver_id' => 4,
                    'message' => 'Your milestone payment request has been accepted by',
                    'link' => '/sent-milestone-requests',
                    'created_at' => '2023-07-26 13:41:53',
                    'updated_at' => '2023-07-26 13:41:53',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            69 =>
                array(
                    'id' => 70,
                    'notification_type' => 'milestone_payments_done_to_admin',
                    'sender_id' => 5,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment request has been accepted by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-07-26 13:41:58',
                    'updated_at' => '2023-07-26 13:41:58',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            70 =>
                array(
                    'id' => 71,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 5,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/university-research20230726-014535',
                    'created_at' => '2023-07-26 13:45:35',
                    'updated_at' => '2023-07-26 13:45:35',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            71 =>
                array(
                    'id' => 72,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 5,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/hiring-a-photo-anywhere-expert20230726-020339',
                    'created_at' => '2023-07-26 14:03:39',
                    'updated_at' => '2023-07-26 14:03:39',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            72 =>
                array(
                    'id' => 73,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 7,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/you-will-get-original-content-with-quality-research-research-review-summary-article20230727-113051',
                    'created_at' => '2023-07-27 11:30:51',
                    'updated_at' => '2023-07-27 11:30:51',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            73 =>
                array(
                    'id' => 74,
                    'notification_type' => 'project_created_by_client',
                    'sender_id' => 15,
                    'receiver_id' => 0,
                    'message' => 'A new Project has been created by',
                    'link' => '/project/you-will-get-original-content-with-quality-research-research-review-summary-article20230727-113329',
                    'created_at' => '2023-07-27 11:33:29',
                    'updated_at' => '2023-07-27 11:33:29',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            74 =>
                array(
                    'id' => 75,
                    'notification_type' => 'freelancer_bid_on_project',
                    'sender_id' => 6,
                    'receiver_id' => 15,
                    'message' => 'A new bid has been submitted by',
                    'link' => '/project/you-will-get-original-content-with-quality-research-research-review-summary-article20230727-113329',
                    'created_at' => '2023-07-27 14:28:49',
                    'updated_at' => '2023-09-20 16:12:50',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 1,
                ),
            75 =>
                array(
                    'id' => 76,
                    'notification_type' => 'freelancer_proposal_for_project',
                    'sender_id' => 5,
                    'receiver_id' => 4,
                    'message' => 'You have recieved a proposal for a project by',
                    'link' => '/project/writing-and-editing20230802-114156',
                    'created_at' => '2023-08-02 11:41:56',
                    'updated_at' => '2023-08-02 11:41:56',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            76 =>
                array(
                    'id' => 77,
                    'notification_type' => 'freelancer_bid_on_project',
                    'sender_id' => 6,
                    'receiver_id' => 7,
                    'message' => 'A new bid has been submitted by',
                    'link' => '/project/you-will-get-original-content-with-quality-research-research-review-summary-article20230727-113051',
                    'created_at' => '2023-08-09 19:52:18',
                    'updated_at' => '2023-08-09 19:52:18',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            77 =>
                array(
                    'id' => 78,
                    'notification_type' => 'freelancer_bid_on_project',
                    'sender_id' => 6,
                    'receiver_id' => 5,
                    'message' => 'A new bid has been submitted by',
                    'link' => '/project/hiring-a-photo-anywhere-expert20230726-020339',
                    'created_at' => '2023-08-09 19:55:57',
                    'updated_at' => '2023-08-09 19:55:57',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            78 =>
                array(
                    'id' => 79,
                    'notification_type' => 'freelancer_hired_for_project',
                    'sender_id' => 5,
                    'receiver_id' => 6,
                    'message' => 'You have been hired for a project by',
                    'link' => '/project/hiring-a-photo-anywhere-expert20230726-020339',
                    'created_at' => '2023-08-09 19:58:12',
                    'updated_at' => '2023-08-09 19:58:12',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            79 =>
                array(
                    'id' => 80,
                    'notification_type' => 'milestone_payment_request_to_client',
                    'sender_id' => 6,
                    'receiver_id' => 5,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/recieved-milestone-requests',
                    'created_at' => '2023-08-09 19:59:19',
                    'updated_at' => '2023-08-09 19:59:19',
                    'showing_panel' => 'client',
                    'seen_by_receiver' => 0,
                ),
            80 =>
                array(
                    'id' => 81,
                    'notification_type' => 'milestone_payment_request_to_admin',
                    'sender_id' => 6,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment has been requested by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-08-09 19:59:24',
                    'updated_at' => '2023-08-09 19:59:24',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            81 =>
                array(
                    'id' => 82,
                    'notification_type' => 'milestone_payments_done_to_freelancer',
                    'sender_id' => 5,
                    'receiver_id' => 6,
                    'message' => 'Your milestone payment request has been accepted by',
                    'link' => '/sent-milestone-requests',
                    'created_at' => '2023-08-09 20:00:38',
                    'updated_at' => '2023-08-09 20:00:38',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
            82 =>
                array(
                    'id' => 83,
                    'notification_type' => 'milestone_payments_done_to_admin',
                    'sender_id' => 5,
                    'receiver_id' => 0,
                    'message' => 'A milestone payment request has been accepted by',
                    'link' => '/admin/all-project-payments',
                    'created_at' => '2023-08-09 20:00:42',
                    'updated_at' => '2023-08-09 20:00:42',
                    'showing_panel' => 'admin',
                    'seen_by_receiver' => 0,
                ),
            83 =>
                array(
                    'id' => 84,
                    'notification_type' => 'project_completed_by_client',
                    'sender_id' => 5,
                    'receiver_id' => 6,
                    'message' => 'A Project has been marked as completed by',
                    'link' => '/project/hiring-a-photo-anywhere-expert20230726-020339',
                    'created_at' => '2023-08-09 20:01:14',
                    'updated_at' => '2023-08-09 20:01:14',
                    'showing_panel' => 'freelancer',
                    'seen_by_receiver' => 0,
                ),
        ));
    }
}
