<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class UserProfilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::table('user_profiles')->delete();

        DB::table('user_profiles')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'user_id' => 4,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 132,
                    'specialist' => '3',
                    'bio' => 'Reach me out to get assistance in your project, I am an experience consultant',
                    'skills' => '["28","37","43","44","46"]',
                    'languages' => 'Turkish',
                    'hourly_rate' => 50.0,
                    'balance' => 48.0,
                    'rating' => 4.0,
                    'created_at' => '2023-04-05 09:10:10',
                    'updated_at' => '2023-07-26 13:41:53',
                    'deleted_at' => NULL,
                ),
            1 =>
                array(
                    'id' => 2,
                    'user_id' => 5,
                    'user_role_id' => NULL,
                    'gender' => NULL,
                    'nationality' => NULL,
                    'specialist' => NULL,
                    'bio' => NULL,
                    'skills' => NULL,
                    'languages' => 'English',
                    'hourly_rate' => NULL,
                    'balance' => 50.0,
                    'rating' => 5.0,
                    'created_at' => '2023-04-05 09:11:20',
                    'updated_at' => '2023-07-24 11:58:58',
                    'deleted_at' => NULL,
                ),
            2 =>
                array(
                    'id' => 3,
                    'user_id' => 6,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'ca',
                    'specialist' => '2',
                    'bio' => 'Hi I am an experienced mentor. I have 20 years of academic experience in various field',
                    'skills' => '["9","10","12","13","15"]',
                    'languages' => 'Italian',
                    'hourly_rate' => 55.0,
                    'balance' => 1401.5,
                    'rating' => 5.0,
                    'created_at' => '2023-04-06 13:09:05',
                    'updated_at' => '2023-08-09 20:00:38',
                    'deleted_at' => NULL,
                ),
            3 =>
                array(
                    'id' => 4,
                    'user_id' => 7,
                    'user_role_id' => NULL,
                    'gender' => NULL,
                    'nationality' => NULL,
                    'specialist' => NULL,
                    'bio' => NULL,
                    'skills' => NULL,
                    'languages' => 'Spanish',
                    'hourly_rate' => NULL,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-06 14:08:19',
                    'updated_at' => '2023-04-06 14:08:19',
                    'deleted_at' => NULL,
                ),
            4 =>
                array(
                    'id' => 5,
                    'user_id' => 8,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'in',
                    'specialist' => '8',
                    'bio' => 'Based on my industry experience, I can give you the best assistance in your desire scope',
                    'skills' => '["9","11","15","17","22"]',
                    'languages' => 'Russian',
                    'hourly_rate' => 35.0,
                    'balance' => 270.0,
                    'rating' => 5.0,
                    'created_at' => '2023-04-06 17:49:15',
                    'updated_at' => '2023-09-17 18:42:52',
                    'deleted_at' => NULL,
                ),
            5 =>
                array(
                    'id' => 6,
                    'user_id' => 9,
                    'user_role_id' => NULL,
                    'gender' => NULL,
                    'nationality' => NULL,
                    'specialist' => NULL,
                    'bio' => NULL,
                    'skills' => NULL,
                    'languages' => 'Russian',
                    'hourly_rate' => NULL,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-06 17:50:42',
                    'updated_at' => '2023-04-06 17:50:42',
                    'deleted_at' => NULL,
                ),
            6 =>
                array(
                    'id' => 7,
                    'user_id' => 10,
                    'user_role_id' => NULL,
                    'gender' => NULL,
                    'nationality' => NULL,
                    'specialist' => NULL,
                    'bio' => NULL,
                    'skills' => NULL,
                    'languages' => 'English',
                    'hourly_rate' => NULL,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-06 18:56:03',
                    'updated_at' => '2023-04-06 18:56:03',
                    'deleted_at' => NULL,
                ),
            7 =>
                array(
                    'id' => 8,
                    'user_id' => 11,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'ba',
                    'specialist' => '4',
                    'bio' => 'Hello',
                    'skills' => '["3","4","5","6","24"]',
                    'languages' => 'English',
                    'hourly_rate' => 100.0,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-07 09:14:24',
                    'updated_at' => '2023-04-07 09:24:30',
                    'deleted_at' => NULL,
                ),
            8 =>
                array(
                    'id' => 9,
                    'user_id' => 12,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'no',
                    'specialist' => '4',
                    'bio' => 'Hi, I\'m a professional, islam here. Seeking a position to utilize my skills and abilities in projects that offer professional growth.

I can provide the best services for guest posting, blogger outreach, EDU Scholarship link building, and Non-content link building. consultant.',
                    'skills' => '["13","14","15","17","23"]',
                    'languages' => 'English',
                    'hourly_rate' => 50.0,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-13 18:14:27',
                    'updated_at' => '2023-06-07 05:35:16',
                    'deleted_at' => NULL,
                ),
            9 =>
                array(
                    'id' => 10,
                    'user_id' => 13,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'ba',
                    'specialist' => '7',
                    'bio' => 'I am ready to serve you anything related you scholarship applications.',
                    'skills' => '["17","23","26","39","47"]',
                    'languages' => 'Spanish',
                    'hourly_rate' => 50.0,
                    'balance' => 200.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-14 11:25:49',
                    'updated_at' => '2023-06-07 05:19:58',
                    'deleted_at' => NULL,
                ),
            10 =>
                array(
                    'id' => 11,
                    'user_id' => 14,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 132,
                    'specialist' => '9',
                    'bio' => 'I have worked with international nonprofits and companies in various roles offering registration, event coordination and scholarship program support.',
                    'skills' => '["9","26","37","39","47"]',
                    'languages' => 'Italian',
                    'hourly_rate' => 100.0,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-14 11:55:59',
                    'updated_at' => '2023-06-07 04:19:03',
                    'deleted_at' => NULL,
                ),
            11 =>
                array(
                    'id' => 12,
                    'user_id' => 15,
                    'user_role_id' => NULL,
                    'gender' => NULL,
                    'nationality' => NULL,
                    'specialist' => NULL,
                    'bio' => NULL,
                    'skills' => NULL,
                    'languages' => 'Turkish',
                    'hourly_rate' => NULL,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-14 13:00:21',
                    'updated_at' => '2023-04-14 13:00:21',
                    'deleted_at' => NULL,
                ),
            12 =>
                array(
                    'id' => 13,
                    'user_id' => 16,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'be',
                    'specialist' => '6',
                    'bio' => 'Reach me out to get assistance in your project, I am an experience consultant',
                    'skills' => '["14","15","21","25","26"]',
                    'languages' => NULL,
                    'hourly_rate' => 45.0,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-15 12:15:20',
                    'updated_at' => '2023-06-07 05:40:25',
                    'deleted_at' => NULL,
                ),
            13 =>
                array(
                    'id' => 14,
                    'user_id' => 17,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'bd',
                    'specialist' => '5',
                    'bio' => 'Hi! I am an experienced consultant, working in this field for over 15 years.  So, if you have any confusion please make sure to inbox me, I\'ll try my best to convince you. Thank you for visiting my profile :)',
                    'skills' => '["9","11","12","14","17"]',
                    'languages' => NULL,
                    'hourly_rate' => 50.0,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-15 14:06:35',
                    'updated_at' => '2023-06-07 04:42:20',
                    'deleted_at' => NULL,
                ),
            14 =>
                array(
                    'id' => 15,
                    'user_id' => 18,
                    'user_role_id' => NULL,
                    'gender' => NULL,
                    'nationality' => NULL,
                    'specialist' => NULL,
                    'bio' => NULL,
                    'skills' => NULL,
                    'languages' => NULL,
                    'hourly_rate' => NULL,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-15 17:14:19',
                    'updated_at' => '2023-04-15 17:14:19',
                    'deleted_at' => NULL,
                ),
            15 =>
                array(
                    'id' => 16,
                    'user_id' => 19,
                    'user_role_id' => NULL,
                    'gender' => 'female',
                    'nationality' => 132,
                    'specialist' => '4',
                    'bio' => 'Hi! I am a consultant, working in this field for over 5 years. This whole encounter prepared me to do my work perfectly and satisfy my client.',
                    'skills' => '["17","40","44","46","47"]',
                    'languages' => NULL,
                    'hourly_rate' => 40.0,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-04-15 17:37:40',
                    'updated_at' => '2023-06-07 04:39:25',
                    'deleted_at' => NULL,
                ),
            16 =>
                array(
                    'id' => 17,
                    'user_id' => 20,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'ar',
                    'specialist' => '6',
                    'bio' => 'Based on my research experience, I can give you the best assistance in your desire scope',
                    'skills' => '["14","17","22","25","37"]',
                    'languages' => NULL,
                    'hourly_rate' => 50.0,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-05-11 23:43:44',
                    'updated_at' => '2023-06-07 04:47:29',
                    'deleted_at' => NULL,
                ),
            17 =>
                array(
                    'id' => 18,
                    'user_id' => 21,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'au',
                    'specialist' => '5',
                    'bio' => 'Based on my industry experience, I can give you the best assistance in your desire scope',
                    'skills' => '["12","14","22","26","37"]',
                    'languages' => NULL,
                    'hourly_rate' => 60.0,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-05-21 18:57:52',
                    'updated_at' => '2023-06-07 05:44:05',
                    'deleted_at' => NULL,
                ),
            18 =>
                array(
                    'id' => 19,
                    'user_id' => 22,
                    'user_role_id' => NULL,
                    'gender' => 'male',
                    'nationality' => 'au',
                    'specialist' => '8',
                    'bio' => 'Reach me out for your career mentoring for your academic programs.',
                    'skills' => '["10","11","17","20","26"]',
                    'languages' => NULL,
                    'hourly_rate' => 45.0,
                    'balance' => 0.0,
                    'rating' => 0.0,
                    'created_at' => '2023-06-05 09:06:58',
                    'updated_at' => '2023-06-07 05:29:21',
                    'deleted_at' => NULL,
                ),
            19 =>
                array(
                    'id' => 20,
                    'user_id' => 23,
                    'user_role_id' => NULL,
                    'gender' => NULL,
                    'nationality' => NULL,
                    'specialist' => NULL,
                    'bio' => NULL,
                    'skills' => NULL,
                    'languages' => NULL,
                    'hourly_rate' => NULL,
                    'balance' => 0.0,
                    'rating' => 5.0,
                    'created_at' => '2023-06-07 03:44:37',
                    'updated_at' => '2023-07-05 13:39:33',
                    'deleted_at' => NULL,
                ),
        ));
    }
}
